import Handlebars from 'handlebars';
import type { Project } from './types.js';

const template = Handlebars.compile(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{intake.companyName}} campaign review</title><style>
:root{--gold:#e8c97a;--bg:#090a0a;--panel:#121414;--line:#2a2d2c;--ink:#f4f0e8;--muted:#8d918d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:42px 24px 100px}.top{display:flex;justify-content:space-between;gap:25px;align-items:center;padding-bottom:30px;border-bottom:1px solid var(--line)}.brand{font-weight:800}.status{color:var(--gold);font-size:12px;text-transform:uppercase;letter-spacing:.1em}h1{font:400 clamp(38px,6vw,70px)/1.05 Georgia,serif;max-width:800px;margin:70px 0 18px}.lead{color:var(--muted);font-size:18px;line-height:1.7;max-width:760px}.grid{display:grid;grid-template-columns:1fr 320px;gap:28px;margin-top:55px}.card{background:var(--panel);border:1px solid var(--line);padding:28px;margin-bottom:16px}.card small{color:var(--gold);text-transform:uppercase;letter-spacing:.12em}.card h2{font:400 28px Georgia,serif}.card p{color:#a6aaa6;line-height:1.7;white-space:pre-line}.aside{position:sticky;top:20px;height:max-content}.score{font-size:58px;color:var(--gold);font-weight:800}.actions textarea{width:100%;min-height:120px;background:#0c0d0d;color:var(--ink);border:1px solid var(--line);padding:13px;margin:13px 0;font:inherit}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px}.buttons button{border:1px solid var(--line);background:transparent;color:var(--ink);padding:13px;font-weight:700}.buttons .approve{background:var(--gold);color:#090a0a;border-color:var(--gold)}@media(max-width:800px){.grid{grid-template-columns:1fr}.aside{position:static}}</style></head><body><main class="wrap"><header class="top"><span class="brand">AdForge × {{intake.companyName}}</span><span class="status">{{status}}</span></header><h1>{{bundle.title}}</h1><p class="lead">{{bundle.subtitle}}</p><div class="grid"><section>{{#each bundle.sections}}<article class="card"><small>{{eyebrow}}</small><h2>{{title}}</h2>{{#each body}}<p>{{this}}</p>{{/each}}{{#if pullQuote}}<p><em>“{{pullQuote}}”</em> {{sourceTimestamp}}</p>{{/if}}</article>{{/each}}</section><aside class="aside"><div class="card"><small>Quality score</small><div class="score">{{quality.score}}</div>{{#each quality.checks}}<p>{{status}} — {{name}}</p>{{/each}}</div><form class="card actions" method="post" action="/api/review/{{reviewToken}}"><small>One consolidated review</small><textarea name="note" placeholder="Collect every requested change here..."></textarea><div class="buttons"><button name="decision" value="revise">Request revision</button><button class="approve" name="decision" value="approve">Approve campaign</button></div></form></aside></div></main></body></html>`);

export function renderReviewPage(project: Project): string {
  return template(project);
}
